version: "3.9"
services:
  postgres:
    container_name: dyplom_postgres
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: "chat"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
